name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '0 6 * * *' # every night at 6 am UTC 1 am UTC-5

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: '2 days'
