name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '0 20 * * *' # every night at 1 am UTC

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: '1 day'
